"use client";

import { motion } from "motion/react";
import { Sparkles, Download, Copy, Check } from "lucide-react";
import { useState } from "react";
import { cn } from "@/lib/cn";
import ScoreBadge from "./ScoreBadge";

function aspectClass(a) {
  if (a === "1:1") return "aspect-square";
  if (a === "4:5") return "aspect-[4/5]";
  if (a === "9:16") return "aspect-[9/16]";
  return "aspect-[16/9]";
}

export default function BannerCard({ result, isWinner, aspect = "16:9", index = 0 }) {
  const [copied, setCopied] = useState(false);

  const onCopy = async () => {
    if (!result.imageUrl) return;
    try {
      await navigator.clipboard.writeText(result.imageUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {}
  };

  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 12, scale: 0.98 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      transition={{ duration: 0.4, delay: index * 0.06, ease: [0.21, 0.47, 0.32, 0.98] }}
      className={cn(
        "group relative overflow-hidden rounded-2xl border bg-surface transition-all duration-300",
        isWinner
          ? "border-[var(--primary)]/60 ring-1 ring-[var(--primary)]/40 shadow-[0_8px_32px_-12px_color-mix(in_oklab,var(--primary)_40%,transparent)]"
          : "border-border hover:border-border-strong",
      )}
    >
      {isWinner && (
        <div className="absolute left-3 top-3 z-10 inline-flex items-center gap-1 rounded-full bg-primary px-2.5 py-1 text-[11px] font-semibold text-primary-fg shadow-lg">
          <Sparkles className="h-3 w-3" strokeWidth={2.5} />
          Selected
        </div>
      )}

      <div
        className={cn(
          aspectClass(aspect),
          "w-full relative bg-gradient-to-br",
          result.previewGradient || "from-violet-500/30 to-cyan-400/30",
        )}
      >
        {result.imageUrl ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={result.imageUrl}
            alt={`Generated by ${result.modelLabel}`}
            className="h-full w-full object-cover"
          />
        ) : (
          <div className="absolute inset-0 flex items-center justify-center">
            <span className="rounded-full bg-black/40 px-3 py-1 text-[11px] font-mono text-white/70 backdrop-blur">
              {result.modelLabel}
            </span>
          </div>
        )}

        {/* Hover actions */}
        <div className="absolute inset-x-0 bottom-0 flex items-center justify-end gap-1.5 bg-gradient-to-t from-black/60 to-transparent p-3 opacity-0 transition-opacity duration-200 group-hover:opacity-100">
          <button
            type="button"
            onClick={onCopy}
            className="inline-flex h-8 items-center gap-1.5 rounded-md bg-white/10 px-2.5 text-[11px] text-white backdrop-blur hover:bg-white/20"
          >
            {copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
            {copied ? "Copied" : "Copy URL"}
          </button>
          <button
            type="button"
            className="inline-flex h-8 items-center gap-1.5 rounded-md bg-white/10 px-2.5 text-[11px] text-white backdrop-blur hover:bg-white/20"
          >
            <Download className="h-3 w-3" />
            Download
          </button>
        </div>
      </div>

      <div className="flex items-center justify-between gap-3 border-t border-border bg-surface-2 px-3 py-2.5 text-xs">
        <div className="min-w-0">
          <div className="truncate text-foreground">{result.modelLabel}</div>
          <div className="truncate text-[10px] text-muted">
            {result.provider} · {result.latencyMs}ms
          </div>
        </div>
        <ScoreBadge score={result.score} />
      </div>
    </motion.div>
  );
}
