// src/components/generate/PromptForm.jsx
"use client";

import { useEffect, useState } from "react";
import { ArrowRight, Loader2, Sparkles } from "lucide-react";
import { useAuth } from "@/components/layout/AuthProvider";
import { listAspectRatios } from "@/lib/db/aspects";
import { listBannerStyles } from "@/lib/db/styles";
import { getDefaultTextModel } from "@/lib/db/models";
import { useCachedQuery } from "@/lib/cache";
import Card from "@/components/ui/Card";
import Button from "@/components/ui/Button";
import PromptInput from "./PromptInput";
import AspectSelector from "./AspectSelector";
import StyleSelector from "./StyleSelector";

// HTML banner studio. Pulls aspects + styles + default text model from DB
// (with stale-while-revalidate caching so opening the page is instant
// after the first visit) and submits to /api/banners.
export default function PromptForm({ onSubmit, isGenerating }) {
  const { supabase } = useAuth();

  const [prompt, setPrompt] = useState("");
  const [aspect, setAspect] = useState(null);
  const [style, setStyle] = useState(null);

  // Catalog data is admin-managed and rarely changes. Cache for 5 minutes
  // and revalidate in the background — the form re-renders if a new
  // aspect / style is added between visits.
  const aspectsQ = useCachedQuery(
    ["catalog", "aspects"],
    () => listAspectRatios(supabase),
    { ttlMs: 5 * 60_000, tags: ["aspects"] },
  );
  const stylesQ = useCachedQuery(
    ["catalog", "styles"],
    () => listBannerStyles(supabase),
    { ttlMs: 5 * 60_000, tags: ["styles"] },
  );
  const textModelQ = useCachedQuery(
    ["catalog", "default-text-model"],
    () => getDefaultTextModel(supabase),
    { ttlMs: 5 * 60_000, tags: ["models"] },
  );

  const aspects   = aspectsQ.data;
  const styles    = stylesQ.data;
  const textModel = textModelQ.data;
  const loadError = aspectsQ.error || stylesQ.error || textModelQ.error;

  // Initialize selected aspect / style once the catalog loads.
  useEffect(() => {
    if (aspect == null && aspects?.length) setAspect(aspects[0].ratio);
  }, [aspect, aspects]);
  useEffect(() => {
    if (style == null && styles?.length) setStyle(styles[0].label);
  }, [style, styles]);

  const ready = aspects && styles;
  const canSubmit =
    !isGenerating && prompt.trim() && aspect && style && ready;

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!canSubmit) return;
    onSubmit({ prompt: prompt.trim(), aspect, style });
  };

  return (
    <Card elevated as="form" className="p-5 md:p-6 space-y-6">
      <PromptInput value={prompt} onChange={setPrompt} />

      {!ready ? (
        <div className="flex items-center gap-2 text-xs text-muted">
          <Loader2 className="h-3.5 w-3.5 animate-spin" /> Loading catalog…
        </div>
      ) : loadError ? (
        <div className="rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-xs text-red-300">
          {loadError}
        </div>
      ) : (
        <>
          <div className="grid gap-5 md:grid-cols-2">
            <AspectSelector
              options={aspects}
              value={aspect}
              onChange={setAspect}
            />
            <StyleSelector
              options={styles}
              value={style}
              onChange={setStyle}
            />
          </div>

          <div className="rounded-xl border border-border bg-background px-3.5 py-3">
            <div className="flex items-start gap-3">
              <span className="mt-0.5 inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-[color-mix(in_oklab,var(--primary)_14%,transparent)] text-primary">
                <Sparkles className="h-3.5 w-3.5" />
              </span>
              <div className="min-w-0 text-xs">
                <div className="text-foreground">
                  Generated by{" "}
                  <span className="font-medium">
                    {textModel?.label || "fallback template"}
                  </span>
                </div>
                <div className="text-muted">
                  {textModel
                    ? `${textModel.provider} · ${textModel.modelId}`
                    : "Configure a default text model in Admin → Models to use OpenRouter."}
                </div>
              </div>
            </div>
          </div>
        </>
      )}

      <div className="divider-soft" />

      <div className="flex items-center justify-between gap-3">
        <p className="text-[11px] text-muted">
          Saves directly to your banners. Edit further in the builder.
        </p>
        <Button
          type="submit"
          size="lg"
          disabled={!canSubmit}
          onClick={handleSubmit}
          rightIcon={
            isGenerating ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <ArrowRight className="h-4 w-4" strokeWidth={2.5} />
            )
          }
        >
          {isGenerating ? "Generating" : "Generate banner"}
        </Button>
      </div>
    </Card>
  );
}
