import Container from "@/components/ui/Container";

export const metadata = {
  title: "Terms of Service | Nanozen",
  description: "Terms of Service for Nanozen.",
};

export default function TermsOfService() {
  return (
    <div className="relative pt-32 pb-24 lg:pt-40 lg:pb-32 overflow-hidden">
      <div className="absolute inset-0 -z-10 overflow-hidden pointer-events-none">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-[radial-gradient(ellipse_at_top,color-mix(in_oklab,var(--primary)_8%,transparent),transparent_70%)]" />
      </div>

      <Container className="max-w-3xl relative z-10">
        <div className="space-y-8">
          <div className="border-b border-border pb-8">
            <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl">Terms of Service</h1>
            <p className="mt-4 text-base text-muted">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
          </div>

          <div className="space-y-8 text-muted-strong leading-relaxed">
            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">1. Agreement to Terms</h2>
              <p>
                By accessing or using Nanozen ("Platform"), operated by GemAI Pvt. Ltd. ("Company", "we", "us", or "our"), you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you do not have permission to access the Service.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">2. Description of Service</h2>
              <p>
                Nanozen is an AI-powered banner generation platform that allows users to create, edit, and export marketing banners using artificial intelligence models. The Service includes banner generation, a visual drag-and-drop builder, and related features.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">3. User Accounts</h2>
              <ul className="list-disc pl-5 space-y-2 text-muted">
                <li>You must be at least 18 years old to use this Service.</li>
                <li>You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.</li>
                <li>You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">4. User Content & Acceptable Use</h2>
              <p>You retain all your rights to any content you submit, post or display on or through the Service ("User Content"). By submitting User Content, you grant us the right to use and process it to operate the Service.</p>
              <p className="mt-2 text-foreground font-medium">You agree not to use the Service to:</p>
              <ul className="list-disc pl-5 space-y-2 text-muted">
                <li>Generate or distribute illegal, abusive, harassing, or sexually explicit content.</li>
                <li>Violate the intellectual property rights of others. Uploading copyrighted images without permission is strictly prohibited.</li>
                <li>Attempt to bypass, exploit, or disrupt the platform's AI models or scoring systems.</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">5. AI-Generated Output</h2>
              <p>
                The banners and HTML/CSS generated by the Service ("Outputs") are provided to you for your commercial and personal use. However, due to the nature of machine learning, the Service may generate incorrect, inappropriate, or similar Outputs for different users. We do not guarantee the uniqueness or copyrightability of any Output.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">6. Limitation of Liability</h2>
              <p>
                In no event shall GemAI Pvt. Ltd., nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">7. Contact Information</h2>
              <p>
                If you have any questions about these Terms, please contact us at <a href="mailto:legal@nanozen.com" className="text-primary transition-colors hover:text-primary/80 hover:underline">legal@nanozen.com</a>.
              </p>
            </section>
          </div>
        </div>
      </Container>
    </div>
  );
}
