-- ============================================================================
-- 0005_banner_editor_columns.sql
--
-- Adds the HTML editor columns to the banners table so that:
--   1. /api/banners persists the AI-generated template in one shot.
--   2. The editor page can hydrate from the stored template instead of
--      re-calling OpenRouter on every visit.
--   3. BannerThumb can render the actual HTML for correct thumbnails.
-- ============================================================================

alter table public.banners
  add column if not exists html      text,
  add column if not exists css       text,
  add column if not exists fields    jsonb,
  add column if not exists alignment text not null default 'left';

comment on column public.banners.html      is 'Banner markup generated by the text model.';
comment on column public.banners.css       is 'Banner styles generated by the text model.';
comment on column public.banners.fields    is 'Editable field definitions (text / color / range / select / toggle).';
comment on column public.banners.alignment is 'Layout alignment: left | center | right.';

notify pgrst, 'reload schema';